### ISSUE TITLE
Indexes at ro_sat and ro_sun

### ISSUE THREAD

**Issue by hkgrov** [ekallevik/flexible_employee_scheduling#30]
We initialise the ro-variables with the sets employees and days, but in the objective function we index them by the sets employees and weeks. We have to decide on how we want to index the variables here

**Comment by ekallevik** [comment]
OptimalityModel is not working in master due to wrong referencing to `time_periods`.  This is fixed in PR #47. To avoid duplication of work and possible merge conflicts this fix won´t be reimplemented. Thus the PR has to be approved and merge before work can continue here. 

I think it is natural to use `weeks` as index to have a consistent and natural indexing scheme.

**Comment by hkgrov** [comment]
fixed in 3ff12d5eb934407c60485e4dc68b0e2b26e7b423
